version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "18:00"
    timezone: Japan
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: activesupport
    versions:
    - 6.1.1
    - 6.1.2.1
    - 6.1.3
  - dependency-name: jbuilder
    versions:
    - 2.11.1
